// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: osmap.proto

#ifndef PROTOBUF_INCLUDED_osmap_2eproto
#define PROTOBUF_INCLUDED_osmap_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_osmap_2eproto 

namespace protobuf_osmap_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[8];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_osmap_2eproto
class SerializedDescriptor;
class SerializedDescriptorDefaultTypeInternal;
extern SerializedDescriptorDefaultTypeInternal _SerializedDescriptor_default_instance_;
class SerializedFeature;
class SerializedFeatureDefaultTypeInternal;
extern SerializedFeatureDefaultTypeInternal _SerializedFeature_default_instance_;
class SerializedK;
class SerializedKDefaultTypeInternal;
extern SerializedKDefaultTypeInternal _SerializedK_default_instance_;
class SerializedKeyframe;
class SerializedKeyframeDefaultTypeInternal;
extern SerializedKeyframeDefaultTypeInternal _SerializedKeyframe_default_instance_;
class SerializedKeypoint;
class SerializedKeypointDefaultTypeInternal;
extern SerializedKeypointDefaultTypeInternal _SerializedKeypoint_default_instance_;
class SerializedMappoint;
class SerializedMappointDefaultTypeInternal;
extern SerializedMappointDefaultTypeInternal _SerializedMappoint_default_instance_;
class SerializedPose;
class SerializedPoseDefaultTypeInternal;
extern SerializedPoseDefaultTypeInternal _SerializedPose_default_instance_;
class SerializedPosition;
class SerializedPositionDefaultTypeInternal;
extern SerializedPositionDefaultTypeInternal _SerializedPosition_default_instance_;
namespace google {
namespace protobuf {
template<> ::SerializedDescriptor* Arena::CreateMaybeMessage<::SerializedDescriptor>(Arena*);
template<> ::SerializedFeature* Arena::CreateMaybeMessage<::SerializedFeature>(Arena*);
template<> ::SerializedK* Arena::CreateMaybeMessage<::SerializedK>(Arena*);
template<> ::SerializedKeyframe* Arena::CreateMaybeMessage<::SerializedKeyframe>(Arena*);
template<> ::SerializedKeypoint* Arena::CreateMaybeMessage<::SerializedKeypoint>(Arena*);
template<> ::SerializedMappoint* Arena::CreateMaybeMessage<::SerializedMappoint>(Arena*);
template<> ::SerializedPose* Arena::CreateMaybeMessage<::SerializedPose>(Arena*);
template<> ::SerializedPosition* Arena::CreateMaybeMessage<::SerializedPosition>(Arena*);
}  // namespace protobuf
}  // namespace google

// ===================================================================

class SerializedDescriptor : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:SerializedDescriptor) */ {
 public:
  SerializedDescriptor();
  virtual ~SerializedDescriptor();

  SerializedDescriptor(const SerializedDescriptor& from);

  inline SerializedDescriptor& operator=(const SerializedDescriptor& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  SerializedDescriptor(SerializedDescriptor&& from) noexcept
    : SerializedDescriptor() {
    *this = ::std::move(from);
  }

  inline SerializedDescriptor& operator=(SerializedDescriptor&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const SerializedDescriptor& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SerializedDescriptor* internal_default_instance() {
    return reinterpret_cast<const SerializedDescriptor*>(
               &_SerializedDescriptor_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(SerializedDescriptor* other);
  friend void swap(SerializedDescriptor& a, SerializedDescriptor& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline SerializedDescriptor* New() const final {
    return CreateMaybeMessage<SerializedDescriptor>(NULL);
  }

  SerializedDescriptor* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<SerializedDescriptor>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const SerializedDescriptor& from);
  void MergeFrom(const SerializedDescriptor& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SerializedDescriptor* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated fixed32 block = 1;
  int block_size() const;
  void clear_block();
  static const int kBlockFieldNumber = 1;
  ::google::protobuf::uint32 block(int index) const;
  void set_block(int index, ::google::protobuf::uint32 value);
  void add_block(::google::protobuf::uint32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      block() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_block();

  // @@protoc_insertion_point(class_scope:SerializedDescriptor)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > block_;
  mutable int _block_cached_byte_size_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_osmap_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class SerializedPose : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:SerializedPose) */ {
 public:
  SerializedPose();
  virtual ~SerializedPose();

  SerializedPose(const SerializedPose& from);

  inline SerializedPose& operator=(const SerializedPose& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  SerializedPose(SerializedPose&& from) noexcept
    : SerializedPose() {
    *this = ::std::move(from);
  }

  inline SerializedPose& operator=(SerializedPose&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const SerializedPose& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SerializedPose* internal_default_instance() {
    return reinterpret_cast<const SerializedPose*>(
               &_SerializedPose_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(SerializedPose* other);
  friend void swap(SerializedPose& a, SerializedPose& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline SerializedPose* New() const final {
    return CreateMaybeMessage<SerializedPose>(NULL);
  }

  SerializedPose* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<SerializedPose>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const SerializedPose& from);
  void MergeFrom(const SerializedPose& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SerializedPose* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated float element = 1;
  int element_size() const;
  void clear_element();
  static const int kElementFieldNumber = 1;
  float element(int index) const;
  void set_element(int index, float value);
  void add_element(float value);
  const ::google::protobuf::RepeatedField< float >&
      element() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_element();

  // @@protoc_insertion_point(class_scope:SerializedPose)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< float > element_;
  mutable int _element_cached_byte_size_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_osmap_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class SerializedPosition : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:SerializedPosition) */ {
 public:
  SerializedPosition();
  virtual ~SerializedPosition();

  SerializedPosition(const SerializedPosition& from);

  inline SerializedPosition& operator=(const SerializedPosition& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  SerializedPosition(SerializedPosition&& from) noexcept
    : SerializedPosition() {
    *this = ::std::move(from);
  }

  inline SerializedPosition& operator=(SerializedPosition&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const SerializedPosition& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SerializedPosition* internal_default_instance() {
    return reinterpret_cast<const SerializedPosition*>(
               &_SerializedPosition_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(SerializedPosition* other);
  friend void swap(SerializedPosition& a, SerializedPosition& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline SerializedPosition* New() const final {
    return CreateMaybeMessage<SerializedPosition>(NULL);
  }

  SerializedPosition* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<SerializedPosition>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const SerializedPosition& from);
  void MergeFrom(const SerializedPosition& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SerializedPosition* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // float x = 1;
  void clear_x();
  static const int kXFieldNumber = 1;
  float x() const;
  void set_x(float value);

  // float y = 2;
  void clear_y();
  static const int kYFieldNumber = 2;
  float y() const;
  void set_y(float value);

  // float z = 3;
  void clear_z();
  static const int kZFieldNumber = 3;
  float z() const;
  void set_z(float value);

  // @@protoc_insertion_point(class_scope:SerializedPosition)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  float x_;
  float y_;
  float z_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_osmap_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class SerializedKeypoint : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:SerializedKeypoint) */ {
 public:
  SerializedKeypoint();
  virtual ~SerializedKeypoint();

  SerializedKeypoint(const SerializedKeypoint& from);

  inline SerializedKeypoint& operator=(const SerializedKeypoint& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  SerializedKeypoint(SerializedKeypoint&& from) noexcept
    : SerializedKeypoint() {
    *this = ::std::move(from);
  }

  inline SerializedKeypoint& operator=(SerializedKeypoint&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const SerializedKeypoint& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SerializedKeypoint* internal_default_instance() {
    return reinterpret_cast<const SerializedKeypoint*>(
               &_SerializedKeypoint_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(SerializedKeypoint* other);
  friend void swap(SerializedKeypoint& a, SerializedKeypoint& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline SerializedKeypoint* New() const final {
    return CreateMaybeMessage<SerializedKeypoint>(NULL);
  }

  SerializedKeypoint* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<SerializedKeypoint>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const SerializedKeypoint& from);
  void MergeFrom(const SerializedKeypoint& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SerializedKeypoint* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // float ptx = 1;
  void clear_ptx();
  static const int kPtxFieldNumber = 1;
  float ptx() const;
  void set_ptx(float value);

  // float pty = 2;
  void clear_pty();
  static const int kPtyFieldNumber = 2;
  float pty() const;
  void set_pty(float value);

  // float angle = 3;
  void clear_angle();
  static const int kAngleFieldNumber = 3;
  float angle() const;
  void set_angle(float value);

  // float octave = 4;
  void clear_octave();
  static const int kOctaveFieldNumber = 4;
  float octave() const;
  void set_octave(float value);

  // @@protoc_insertion_point(class_scope:SerializedKeypoint)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  float ptx_;
  float pty_;
  float angle_;
  float octave_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_osmap_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class SerializedK : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:SerializedK) */ {
 public:
  SerializedK();
  virtual ~SerializedK();

  SerializedK(const SerializedK& from);

  inline SerializedK& operator=(const SerializedK& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  SerializedK(SerializedK&& from) noexcept
    : SerializedK() {
    *this = ::std::move(from);
  }

  inline SerializedK& operator=(SerializedK&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const SerializedK& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SerializedK* internal_default_instance() {
    return reinterpret_cast<const SerializedK*>(
               &_SerializedK_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  void Swap(SerializedK* other);
  friend void swap(SerializedK& a, SerializedK& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline SerializedK* New() const final {
    return CreateMaybeMessage<SerializedK>(NULL);
  }

  SerializedK* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<SerializedK>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const SerializedK& from);
  void MergeFrom(const SerializedK& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SerializedK* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // float fx = 1;
  void clear_fx();
  static const int kFxFieldNumber = 1;
  float fx() const;
  void set_fx(float value);

  // float fy = 2;
  void clear_fy();
  static const int kFyFieldNumber = 2;
  float fy() const;
  void set_fy(float value);

  // float cx = 3;
  void clear_cx();
  static const int kCxFieldNumber = 3;
  float cx() const;
  void set_cx(float value);

  // float cy = 4;
  void clear_cy();
  static const int kCyFieldNumber = 4;
  float cy() const;
  void set_cy(float value);

  // @@protoc_insertion_point(class_scope:SerializedK)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  float fx_;
  float fy_;
  float cx_;
  float cy_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_osmap_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class SerializedMappoint : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:SerializedMappoint) */ {
 public:
  SerializedMappoint();
  virtual ~SerializedMappoint();

  SerializedMappoint(const SerializedMappoint& from);

  inline SerializedMappoint& operator=(const SerializedMappoint& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  SerializedMappoint(SerializedMappoint&& from) noexcept
    : SerializedMappoint() {
    *this = ::std::move(from);
  }

  inline SerializedMappoint& operator=(SerializedMappoint&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const SerializedMappoint& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SerializedMappoint* internal_default_instance() {
    return reinterpret_cast<const SerializedMappoint*>(
               &_SerializedMappoint_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  void Swap(SerializedMappoint* other);
  friend void swap(SerializedMappoint& a, SerializedMappoint& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline SerializedMappoint* New() const final {
    return CreateMaybeMessage<SerializedMappoint>(NULL);
  }

  SerializedMappoint* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<SerializedMappoint>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const SerializedMappoint& from);
  void MergeFrom(const SerializedMappoint& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SerializedMappoint* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .SerializedPosition position = 2;
  bool has_position() const;
  void clear_position();
  static const int kPositionFieldNumber = 2;
  private:
  const ::SerializedPosition& _internal_position() const;
  public:
  const ::SerializedPosition& position() const;
  ::SerializedPosition* release_position();
  ::SerializedPosition* mutable_position();
  void set_allocated_position(::SerializedPosition* position);

  // .SerializedDescriptor descriptor = 5;
  bool has_descriptor() const;
  void clear_descriptor();
  static const int kDescriptorFieldNumber = 5;
  private:
  const ::SerializedDescriptor& _internal_descriptor() const;
  public:
  const ::SerializedDescriptor& descriptor() const;
  ::SerializedDescriptor* release_descriptor();
  ::SerializedDescriptor* mutable_descriptor();
  void set_allocated_descriptor(::SerializedDescriptor* descriptor);

  // uint32 id = 1;
  void clear_id();
  static const int kIdFieldNumber = 1;
  ::google::protobuf::uint32 id() const;
  void set_id(::google::protobuf::uint32 value);

  // float visible = 3;
  void clear_visible();
  static const int kVisibleFieldNumber = 3;
  float visible() const;
  void set_visible(float value);

  // float found = 4;
  void clear_found();
  static const int kFoundFieldNumber = 4;
  float found() const;
  void set_found(float value);

  // @@protoc_insertion_point(class_scope:SerializedMappoint)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::SerializedPosition* position_;
  ::SerializedDescriptor* descriptor_;
  ::google::protobuf::uint32 id_;
  float visible_;
  float found_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_osmap_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class SerializedKeyframe : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:SerializedKeyframe) */ {
 public:
  SerializedKeyframe();
  virtual ~SerializedKeyframe();

  SerializedKeyframe(const SerializedKeyframe& from);

  inline SerializedKeyframe& operator=(const SerializedKeyframe& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  SerializedKeyframe(SerializedKeyframe&& from) noexcept
    : SerializedKeyframe() {
    *this = ::std::move(from);
  }

  inline SerializedKeyframe& operator=(SerializedKeyframe&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const SerializedKeyframe& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SerializedKeyframe* internal_default_instance() {
    return reinterpret_cast<const SerializedKeyframe*>(
               &_SerializedKeyframe_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  void Swap(SerializedKeyframe* other);
  friend void swap(SerializedKeyframe& a, SerializedKeyframe& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline SerializedKeyframe* New() const final {
    return CreateMaybeMessage<SerializedKeyframe>(NULL);
  }

  SerializedKeyframe* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<SerializedKeyframe>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const SerializedKeyframe& from);
  void MergeFrom(const SerializedKeyframe& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SerializedKeyframe* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .SerializedPose pose = 2;
  bool has_pose() const;
  void clear_pose();
  static const int kPoseFieldNumber = 2;
  private:
  const ::SerializedPose& _internal_pose() const;
  public:
  const ::SerializedPose& pose() const;
  ::SerializedPose* release_pose();
  ::SerializedPose* mutable_pose();
  void set_allocated_pose(::SerializedPose* pose);

  // uint32 id = 1;
  void clear_id();
  static const int kIdFieldNumber = 1;
  ::google::protobuf::uint32 id() const;
  void set_id(::google::protobuf::uint32 value);

  // uint32 k = 3;
  void clear_k();
  static const int kKFieldNumber = 3;
  ::google::protobuf::uint32 k() const;
  void set_k(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:SerializedKeyframe)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::SerializedPose* pose_;
  ::google::protobuf::uint32 id_;
  ::google::protobuf::uint32 k_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_osmap_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class SerializedFeature : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:SerializedFeature) */ {
 public:
  SerializedFeature();
  virtual ~SerializedFeature();

  SerializedFeature(const SerializedFeature& from);

  inline SerializedFeature& operator=(const SerializedFeature& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  SerializedFeature(SerializedFeature&& from) noexcept
    : SerializedFeature() {
    *this = ::std::move(from);
  }

  inline SerializedFeature& operator=(SerializedFeature&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const SerializedFeature& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SerializedFeature* internal_default_instance() {
    return reinterpret_cast<const SerializedFeature*>(
               &_SerializedFeature_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    7;

  void Swap(SerializedFeature* other);
  friend void swap(SerializedFeature& a, SerializedFeature& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline SerializedFeature* New() const final {
    return CreateMaybeMessage<SerializedFeature>(NULL);
  }

  SerializedFeature* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<SerializedFeature>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const SerializedFeature& from);
  void MergeFrom(const SerializedFeature& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SerializedFeature* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .SerializedKeypoint keypoint = 3;
  bool has_keypoint() const;
  void clear_keypoint();
  static const int kKeypointFieldNumber = 3;
  private:
  const ::SerializedKeypoint& _internal_keypoint() const;
  public:
  const ::SerializedKeypoint& keypoint() const;
  ::SerializedKeypoint* release_keypoint();
  ::SerializedKeypoint* mutable_keypoint();
  void set_allocated_keypoint(::SerializedKeypoint* keypoint);

  // .SerializedDescriptor descriptor = 4;
  bool has_descriptor() const;
  void clear_descriptor();
  static const int kDescriptorFieldNumber = 4;
  private:
  const ::SerializedDescriptor& _internal_descriptor() const;
  public:
  const ::SerializedDescriptor& descriptor() const;
  ::SerializedDescriptor* release_descriptor();
  ::SerializedDescriptor* mutable_descriptor();
  void set_allocated_descriptor(::SerializedDescriptor* descriptor);

  // uint32 keyframe_id = 1;
  void clear_keyframe_id();
  static const int kKeyframeIdFieldNumber = 1;
  ::google::protobuf::uint32 keyframe_id() const;
  void set_keyframe_id(::google::protobuf::uint32 value);

  // uint32 mappoint_id = 2;
  void clear_mappoint_id();
  static const int kMappointIdFieldNumber = 2;
  ::google::protobuf::uint32 mappoint_id() const;
  void set_mappoint_id(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:SerializedFeature)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::SerializedKeypoint* keypoint_;
  ::SerializedDescriptor* descriptor_;
  ::google::protobuf::uint32 keyframe_id_;
  ::google::protobuf::uint32 mappoint_id_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_osmap_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// SerializedDescriptor

// repeated fixed32 block = 1;
inline int SerializedDescriptor::block_size() const {
  return block_.size();
}
inline void SerializedDescriptor::clear_block() {
  block_.Clear();
}
inline ::google::protobuf::uint32 SerializedDescriptor::block(int index) const {
  // @@protoc_insertion_point(field_get:SerializedDescriptor.block)
  return block_.Get(index);
}
inline void SerializedDescriptor::set_block(int index, ::google::protobuf::uint32 value) {
  block_.Set(index, value);
  // @@protoc_insertion_point(field_set:SerializedDescriptor.block)
}
inline void SerializedDescriptor::add_block(::google::protobuf::uint32 value) {
  block_.Add(value);
  // @@protoc_insertion_point(field_add:SerializedDescriptor.block)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
SerializedDescriptor::block() const {
  // @@protoc_insertion_point(field_list:SerializedDescriptor.block)
  return block_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
SerializedDescriptor::mutable_block() {
  // @@protoc_insertion_point(field_mutable_list:SerializedDescriptor.block)
  return &block_;
}

// -------------------------------------------------------------------

// SerializedPose

// repeated float element = 1;
inline int SerializedPose::element_size() const {
  return element_.size();
}
inline void SerializedPose::clear_element() {
  element_.Clear();
}
inline float SerializedPose::element(int index) const {
  // @@protoc_insertion_point(field_get:SerializedPose.element)
  return element_.Get(index);
}
inline void SerializedPose::set_element(int index, float value) {
  element_.Set(index, value);
  // @@protoc_insertion_point(field_set:SerializedPose.element)
}
inline void SerializedPose::add_element(float value) {
  element_.Add(value);
  // @@protoc_insertion_point(field_add:SerializedPose.element)
}
inline const ::google::protobuf::RepeatedField< float >&
SerializedPose::element() const {
  // @@protoc_insertion_point(field_list:SerializedPose.element)
  return element_;
}
inline ::google::protobuf::RepeatedField< float >*
SerializedPose::mutable_element() {
  // @@protoc_insertion_point(field_mutable_list:SerializedPose.element)
  return &element_;
}

// -------------------------------------------------------------------

// SerializedPosition

// float x = 1;
inline void SerializedPosition::clear_x() {
  x_ = 0;
}
inline float SerializedPosition::x() const {
  // @@protoc_insertion_point(field_get:SerializedPosition.x)
  return x_;
}
inline void SerializedPosition::set_x(float value) {
  
  x_ = value;
  // @@protoc_insertion_point(field_set:SerializedPosition.x)
}

// float y = 2;
inline void SerializedPosition::clear_y() {
  y_ = 0;
}
inline float SerializedPosition::y() const {
  // @@protoc_insertion_point(field_get:SerializedPosition.y)
  return y_;
}
inline void SerializedPosition::set_y(float value) {
  
  y_ = value;
  // @@protoc_insertion_point(field_set:SerializedPosition.y)
}

// float z = 3;
inline void SerializedPosition::clear_z() {
  z_ = 0;
}
inline float SerializedPosition::z() const {
  // @@protoc_insertion_point(field_get:SerializedPosition.z)
  return z_;
}
inline void SerializedPosition::set_z(float value) {
  
  z_ = value;
  // @@protoc_insertion_point(field_set:SerializedPosition.z)
}

// -------------------------------------------------------------------

// SerializedKeypoint

// float ptx = 1;
inline void SerializedKeypoint::clear_ptx() {
  ptx_ = 0;
}
inline float SerializedKeypoint::ptx() const {
  // @@protoc_insertion_point(field_get:SerializedKeypoint.ptx)
  return ptx_;
}
inline void SerializedKeypoint::set_ptx(float value) {
  
  ptx_ = value;
  // @@protoc_insertion_point(field_set:SerializedKeypoint.ptx)
}

// float pty = 2;
inline void SerializedKeypoint::clear_pty() {
  pty_ = 0;
}
inline float SerializedKeypoint::pty() const {
  // @@protoc_insertion_point(field_get:SerializedKeypoint.pty)
  return pty_;
}
inline void SerializedKeypoint::set_pty(float value) {
  
  pty_ = value;
  // @@protoc_insertion_point(field_set:SerializedKeypoint.pty)
}

// float angle = 3;
inline void SerializedKeypoint::clear_angle() {
  angle_ = 0;
}
inline float SerializedKeypoint::angle() const {
  // @@protoc_insertion_point(field_get:SerializedKeypoint.angle)
  return angle_;
}
inline void SerializedKeypoint::set_angle(float value) {
  
  angle_ = value;
  // @@protoc_insertion_point(field_set:SerializedKeypoint.angle)
}

// float octave = 4;
inline void SerializedKeypoint::clear_octave() {
  octave_ = 0;
}
inline float SerializedKeypoint::octave() const {
  // @@protoc_insertion_point(field_get:SerializedKeypoint.octave)
  return octave_;
}
inline void SerializedKeypoint::set_octave(float value) {
  
  octave_ = value;
  // @@protoc_insertion_point(field_set:SerializedKeypoint.octave)
}

// -------------------------------------------------------------------

// SerializedK

// float fx = 1;
inline void SerializedK::clear_fx() {
  fx_ = 0;
}
inline float SerializedK::fx() const {
  // @@protoc_insertion_point(field_get:SerializedK.fx)
  return fx_;
}
inline void SerializedK::set_fx(float value) {
  
  fx_ = value;
  // @@protoc_insertion_point(field_set:SerializedK.fx)
}

// float fy = 2;
inline void SerializedK::clear_fy() {
  fy_ = 0;
}
inline float SerializedK::fy() const {
  // @@protoc_insertion_point(field_get:SerializedK.fy)
  return fy_;
}
inline void SerializedK::set_fy(float value) {
  
  fy_ = value;
  // @@protoc_insertion_point(field_set:SerializedK.fy)
}

// float cx = 3;
inline void SerializedK::clear_cx() {
  cx_ = 0;
}
inline float SerializedK::cx() const {
  // @@protoc_insertion_point(field_get:SerializedK.cx)
  return cx_;
}
inline void SerializedK::set_cx(float value) {
  
  cx_ = value;
  // @@protoc_insertion_point(field_set:SerializedK.cx)
}

// float cy = 4;
inline void SerializedK::clear_cy() {
  cy_ = 0;
}
inline float SerializedK::cy() const {
  // @@protoc_insertion_point(field_get:SerializedK.cy)
  return cy_;
}
inline void SerializedK::set_cy(float value) {
  
  cy_ = value;
  // @@protoc_insertion_point(field_set:SerializedK.cy)
}

// -------------------------------------------------------------------

// SerializedMappoint

// uint32 id = 1;
inline void SerializedMappoint::clear_id() {
  id_ = 0u;
}
inline ::google::protobuf::uint32 SerializedMappoint::id() const {
  // @@protoc_insertion_point(field_get:SerializedMappoint.id)
  return id_;
}
inline void SerializedMappoint::set_id(::google::protobuf::uint32 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:SerializedMappoint.id)
}

// .SerializedPosition position = 2;
inline bool SerializedMappoint::has_position() const {
  return this != internal_default_instance() && position_ != NULL;
}
inline void SerializedMappoint::clear_position() {
  if (GetArenaNoVirtual() == NULL && position_ != NULL) {
    delete position_;
  }
  position_ = NULL;
}
inline const ::SerializedPosition& SerializedMappoint::_internal_position() const {
  return *position_;
}
inline const ::SerializedPosition& SerializedMappoint::position() const {
  const ::SerializedPosition* p = position_;
  // @@protoc_insertion_point(field_get:SerializedMappoint.position)
  return p != NULL ? *p : *reinterpret_cast<const ::SerializedPosition*>(
      &::_SerializedPosition_default_instance_);
}
inline ::SerializedPosition* SerializedMappoint::release_position() {
  // @@protoc_insertion_point(field_release:SerializedMappoint.position)
  
  ::SerializedPosition* temp = position_;
  position_ = NULL;
  return temp;
}
inline ::SerializedPosition* SerializedMappoint::mutable_position() {
  
  if (position_ == NULL) {
    auto* p = CreateMaybeMessage<::SerializedPosition>(GetArenaNoVirtual());
    position_ = p;
  }
  // @@protoc_insertion_point(field_mutable:SerializedMappoint.position)
  return position_;
}
inline void SerializedMappoint::set_allocated_position(::SerializedPosition* position) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete position_;
  }
  if (position) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      position = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, position, submessage_arena);
    }
    
  } else {
    
  }
  position_ = position;
  // @@protoc_insertion_point(field_set_allocated:SerializedMappoint.position)
}

// float visible = 3;
inline void SerializedMappoint::clear_visible() {
  visible_ = 0;
}
inline float SerializedMappoint::visible() const {
  // @@protoc_insertion_point(field_get:SerializedMappoint.visible)
  return visible_;
}
inline void SerializedMappoint::set_visible(float value) {
  
  visible_ = value;
  // @@protoc_insertion_point(field_set:SerializedMappoint.visible)
}

// float found = 4;
inline void SerializedMappoint::clear_found() {
  found_ = 0;
}
inline float SerializedMappoint::found() const {
  // @@protoc_insertion_point(field_get:SerializedMappoint.found)
  return found_;
}
inline void SerializedMappoint::set_found(float value) {
  
  found_ = value;
  // @@protoc_insertion_point(field_set:SerializedMappoint.found)
}

// .SerializedDescriptor descriptor = 5;
inline bool SerializedMappoint::has_descriptor() const {
  return this != internal_default_instance() && descriptor_ != NULL;
}
inline void SerializedMappoint::clear_descriptor() {
  if (GetArenaNoVirtual() == NULL && descriptor_ != NULL) {
    delete descriptor_;
  }
  descriptor_ = NULL;
}
inline const ::SerializedDescriptor& SerializedMappoint::_internal_descriptor() const {
  return *descriptor_;
}
inline const ::SerializedDescriptor& SerializedMappoint::descriptor() const {
  const ::SerializedDescriptor* p = descriptor_;
  // @@protoc_insertion_point(field_get:SerializedMappoint.descriptor)
  return p != NULL ? *p : *reinterpret_cast<const ::SerializedDescriptor*>(
      &::_SerializedDescriptor_default_instance_);
}
inline ::SerializedDescriptor* SerializedMappoint::release_descriptor() {
  // @@protoc_insertion_point(field_release:SerializedMappoint.descriptor)
  
  ::SerializedDescriptor* temp = descriptor_;
  descriptor_ = NULL;
  return temp;
}
inline ::SerializedDescriptor* SerializedMappoint::mutable_descriptor() {
  
  if (descriptor_ == NULL) {
    auto* p = CreateMaybeMessage<::SerializedDescriptor>(GetArenaNoVirtual());
    descriptor_ = p;
  }
  // @@protoc_insertion_point(field_mutable:SerializedMappoint.descriptor)
  return descriptor_;
}
inline void SerializedMappoint::set_allocated_descriptor(::SerializedDescriptor* descriptor) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete descriptor_;
  }
  if (descriptor) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      descriptor = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, descriptor, submessage_arena);
    }
    
  } else {
    
  }
  descriptor_ = descriptor;
  // @@protoc_insertion_point(field_set_allocated:SerializedMappoint.descriptor)
}

// -------------------------------------------------------------------

// SerializedKeyframe

// uint32 id = 1;
inline void SerializedKeyframe::clear_id() {
  id_ = 0u;
}
inline ::google::protobuf::uint32 SerializedKeyframe::id() const {
  // @@protoc_insertion_point(field_get:SerializedKeyframe.id)
  return id_;
}
inline void SerializedKeyframe::set_id(::google::protobuf::uint32 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:SerializedKeyframe.id)
}

// .SerializedPose pose = 2;
inline bool SerializedKeyframe::has_pose() const {
  return this != internal_default_instance() && pose_ != NULL;
}
inline void SerializedKeyframe::clear_pose() {
  if (GetArenaNoVirtual() == NULL && pose_ != NULL) {
    delete pose_;
  }
  pose_ = NULL;
}
inline const ::SerializedPose& SerializedKeyframe::_internal_pose() const {
  return *pose_;
}
inline const ::SerializedPose& SerializedKeyframe::pose() const {
  const ::SerializedPose* p = pose_;
  // @@protoc_insertion_point(field_get:SerializedKeyframe.pose)
  return p != NULL ? *p : *reinterpret_cast<const ::SerializedPose*>(
      &::_SerializedPose_default_instance_);
}
inline ::SerializedPose* SerializedKeyframe::release_pose() {
  // @@protoc_insertion_point(field_release:SerializedKeyframe.pose)
  
  ::SerializedPose* temp = pose_;
  pose_ = NULL;
  return temp;
}
inline ::SerializedPose* SerializedKeyframe::mutable_pose() {
  
  if (pose_ == NULL) {
    auto* p = CreateMaybeMessage<::SerializedPose>(GetArenaNoVirtual());
    pose_ = p;
  }
  // @@protoc_insertion_point(field_mutable:SerializedKeyframe.pose)
  return pose_;
}
inline void SerializedKeyframe::set_allocated_pose(::SerializedPose* pose) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete pose_;
  }
  if (pose) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      pose = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, pose, submessage_arena);
    }
    
  } else {
    
  }
  pose_ = pose;
  // @@protoc_insertion_point(field_set_allocated:SerializedKeyframe.pose)
}

// uint32 k = 3;
inline void SerializedKeyframe::clear_k() {
  k_ = 0u;
}
inline ::google::protobuf::uint32 SerializedKeyframe::k() const {
  // @@protoc_insertion_point(field_get:SerializedKeyframe.k)
  return k_;
}
inline void SerializedKeyframe::set_k(::google::protobuf::uint32 value) {
  
  k_ = value;
  // @@protoc_insertion_point(field_set:SerializedKeyframe.k)
}

// -------------------------------------------------------------------

// SerializedFeature

// uint32 keyframe_id = 1;
inline void SerializedFeature::clear_keyframe_id() {
  keyframe_id_ = 0u;
}
inline ::google::protobuf::uint32 SerializedFeature::keyframe_id() const {
  // @@protoc_insertion_point(field_get:SerializedFeature.keyframe_id)
  return keyframe_id_;
}
inline void SerializedFeature::set_keyframe_id(::google::protobuf::uint32 value) {
  
  keyframe_id_ = value;
  // @@protoc_insertion_point(field_set:SerializedFeature.keyframe_id)
}

// uint32 mappoint_id = 2;
inline void SerializedFeature::clear_mappoint_id() {
  mappoint_id_ = 0u;
}
inline ::google::protobuf::uint32 SerializedFeature::mappoint_id() const {
  // @@protoc_insertion_point(field_get:SerializedFeature.mappoint_id)
  return mappoint_id_;
}
inline void SerializedFeature::set_mappoint_id(::google::protobuf::uint32 value) {
  
  mappoint_id_ = value;
  // @@protoc_insertion_point(field_set:SerializedFeature.mappoint_id)
}

// .SerializedKeypoint keypoint = 3;
inline bool SerializedFeature::has_keypoint() const {
  return this != internal_default_instance() && keypoint_ != NULL;
}
inline void SerializedFeature::clear_keypoint() {
  if (GetArenaNoVirtual() == NULL && keypoint_ != NULL) {
    delete keypoint_;
  }
  keypoint_ = NULL;
}
inline const ::SerializedKeypoint& SerializedFeature::_internal_keypoint() const {
  return *keypoint_;
}
inline const ::SerializedKeypoint& SerializedFeature::keypoint() const {
  const ::SerializedKeypoint* p = keypoint_;
  // @@protoc_insertion_point(field_get:SerializedFeature.keypoint)
  return p != NULL ? *p : *reinterpret_cast<const ::SerializedKeypoint*>(
      &::_SerializedKeypoint_default_instance_);
}
inline ::SerializedKeypoint* SerializedFeature::release_keypoint() {
  // @@protoc_insertion_point(field_release:SerializedFeature.keypoint)
  
  ::SerializedKeypoint* temp = keypoint_;
  keypoint_ = NULL;
  return temp;
}
inline ::SerializedKeypoint* SerializedFeature::mutable_keypoint() {
  
  if (keypoint_ == NULL) {
    auto* p = CreateMaybeMessage<::SerializedKeypoint>(GetArenaNoVirtual());
    keypoint_ = p;
  }
  // @@protoc_insertion_point(field_mutable:SerializedFeature.keypoint)
  return keypoint_;
}
inline void SerializedFeature::set_allocated_keypoint(::SerializedKeypoint* keypoint) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete keypoint_;
  }
  if (keypoint) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      keypoint = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, keypoint, submessage_arena);
    }
    
  } else {
    
  }
  keypoint_ = keypoint;
  // @@protoc_insertion_point(field_set_allocated:SerializedFeature.keypoint)
}

// .SerializedDescriptor descriptor = 4;
inline bool SerializedFeature::has_descriptor() const {
  return this != internal_default_instance() && descriptor_ != NULL;
}
inline void SerializedFeature::clear_descriptor() {
  if (GetArenaNoVirtual() == NULL && descriptor_ != NULL) {
    delete descriptor_;
  }
  descriptor_ = NULL;
}
inline const ::SerializedDescriptor& SerializedFeature::_internal_descriptor() const {
  return *descriptor_;
}
inline const ::SerializedDescriptor& SerializedFeature::descriptor() const {
  const ::SerializedDescriptor* p = descriptor_;
  // @@protoc_insertion_point(field_get:SerializedFeature.descriptor)
  return p != NULL ? *p : *reinterpret_cast<const ::SerializedDescriptor*>(
      &::_SerializedDescriptor_default_instance_);
}
inline ::SerializedDescriptor* SerializedFeature::release_descriptor() {
  // @@protoc_insertion_point(field_release:SerializedFeature.descriptor)
  
  ::SerializedDescriptor* temp = descriptor_;
  descriptor_ = NULL;
  return temp;
}
inline ::SerializedDescriptor* SerializedFeature::mutable_descriptor() {
  
  if (descriptor_ == NULL) {
    auto* p = CreateMaybeMessage<::SerializedDescriptor>(GetArenaNoVirtual());
    descriptor_ = p;
  }
  // @@protoc_insertion_point(field_mutable:SerializedFeature.descriptor)
  return descriptor_;
}
inline void SerializedFeature::set_allocated_descriptor(::SerializedDescriptor* descriptor) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete descriptor_;
  }
  if (descriptor) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      descriptor = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, descriptor, submessage_arena);
    }
    
  } else {
    
  }
  descriptor_ = descriptor;
  // @@protoc_insertion_point(field_set_allocated:SerializedFeature.descriptor)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_osmap_2eproto
